global:
    scrape_interval: 15s
scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["18.207.119.197:9090"]
    - job_name: "node_exporter"
      static_configs:
         - targets: ["18.207.119.197:9100"]
